--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ShockedPlot7560/FactionMaster
build-by-default: true
branches:
- stable
- dev
- pmmp4
- next-minor
- main
projects:
  FactionMaster:
    path: ""
    icon: "icon.png"
...
